// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqyzgpvpcronuxmjulpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxeXpncHZwY3JvbnV4bWp1bHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzY1MTUsImV4cCI6MjA2MjMxMjUxNX0.NruEZoAlmUtkPpq7sa2DgewEy11cKaQ-Qjupw0FVS-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);